<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class exception__StackTools_IntIterator {
	public function __construct($from, $till) {
		if(!php_Boot::$skip_constructor) {
		$this->till = 0;
		$this->current = 0;
		$this->current = $from;
		$this->till = $till;
	}}
	public $current;
	public $till;
	public function hasNext() {
		return $this->current !== $this->till;
	}
	public function next() {
		if($this->current < $this->till) {
			return $this->current++;
		} else {
			return $this->current--;
		}
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'exception._StackTools.IntIterator'; }
}
